/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testffmpeg_FFmpegJni */

#ifndef _Included_com_example_testffmpeg_FFmpegJni
#define _Included_com_example_testffmpeg_FFmpegJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_testffmpeg_FFmpegJni
 * Method:    IGetVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_testffmpeg_FFmpegJni_IGetVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_example_testffmpeg_FFmpegJni
 * Method:    IInit
 * Signature: (Ljava/lang/String;IIII)I
 */
JNIEXPORT jint JNICALL Java_com_example_testffmpeg_FFmpegJni_IInit
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint);

/*
 * Class:     com_example_testffmpeg_FFmpegJni
 * Method:    IResize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_testffmpeg_FFmpegJni_IResize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_testffmpeg_FFmpegJni
 * Method:    IPlay
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_testffmpeg_FFmpegJni_IPlay
  (JNIEnv *, jobject);

/*
 * Class:     com_example_testffmpeg_FFmpegJni
 * Method:    IStop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_testffmpeg_FFmpegJni_IStop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
